spring:
  application:
    name: llamabot
  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3.2
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: postgres
    password: strongpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
