spring:
  application:
    name: llamabot
  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3.2
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: postgres
    password: strongpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret: dvN3YwX0K1x9oUTFNo5NnAJKcgQQQdmKHqiS0ylYcBU=
      expiration-ms: 3600000
    oauth2:
      client:
        registration:
          keycloak:
            client-id: llamabot
            client-secret: N2j9dkq2DvfWw052bMKqm5wyhBMp15bJ
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/myrealm
