spring:
  application:
    name: llamabot
  ai:
    ollama:
      base-url: http://host.docker.internal:11434
      model: llama3.2
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-ms: 3600000
    oauth2:
      client:
        registration:
          keycloak:
            client-id: llamabot
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://keycloak:9090/realms/myrealm
